-- v15: 封板雷达候选落库（抢封板收益闭环）
--
-- 用途：把雷达盘中产出的「刚封板 / 回封候选」首次 sighting 落库，收盘判定是否封住，
-- D+1 拉开盘价算实际收益，让「次日竞价卖出」口径从 preliminary 逐步积累实测样本。
--
-- 口径纪律：
--   · buy_price = 信号首次出现时的现价（回封候选 < 涨停价，即"拉升过程中买入"的入场价）；
--   · realized_return_pct = (D+1 开盘 - buy_price) / buy_price × 100；
--   · sealed_final 只回答"当天封住没有"，与收益独立——炸板也可能正收益、封住也可能负。
--
-- 未跑本迁移时，seize_service 的落库/读回全部静默降级（ingest/close-out/realize 不抛异常，
-- /api/seize/history 返回 enabled:false），不影响雷达实时链路。

CREATE TABLE IF NOT EXISTS seize_radar_log (
  id bigint generated by default as identity primary key,
  trade_date date not null,
  code text not null,
  name text not null default '',
  -- just_sealed = 刚封板窗口命中；reseal = 回封候选
  signal_kind text not null,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  -- 信号首次出现时的现价（首 sighting 固化，重复 sighting 跳过）
  buy_price numeric not null,
  limit_price numeric not null,
  -- 回封候选：信号时距涨停 %；刚封板恒 0
  dist_to_limit_pct numeric,
  -- 收盘判定：该票当天最终是否封住（null = 未判定）
  sealed_final boolean,
  -- D+1 开盘价与相对 buy_price 的收益
  next_open numeric,
  next_open_pct numeric,
  realized_return_pct numeric,
  created_at timestamptz not null default now(),
  -- 同一天同一票同一信号只记首 sighting
  unique (trade_date, code, signal_kind)
);

CREATE INDEX IF NOT EXISTS seize_radar_log_date_idx
  ON seize_radar_log (trade_date DESC);
